[platformio]
boards_dir = boards

[env:stm32f072c8t6]
platform = ststm32
board = stm32f072c8t6
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
lib_archive = no
lib_ldf_mode = deep+
build_flags =
    -DSTM32F072xB
    -DSTM32F0
    -DSTM
    -DF0
    -DCAN_COMPATIBLE
    -Wl,--print-memory-usage

[env:stm32f072c8t6_rev1_pyro]
extends = env:stm32f072c8t6
build_flags =
    ${env:stm32f072c8t6.build_flags}
    -DPLEASC_FIRE_ENABLED=1
    -DREV1_ACCEPTED_RISK=1
